### ISSUE TITLE
pysdl2 gfx not working in termux

### ISSUE THREAD

**Issue by CAPTAIN1947** [py-sdl/py-sdl2#221]
I am trying to use pysdl2 in termux and everything works fine except sdl2.sdlgfx and as soon its imported the following error is raised:- 
Traceback (most recent call last):                                                 4   File "/data/data/com.termux/files/home/test.py", line 1, in <module>             5     import sdl2.sdlgfx                                                             6   File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/sdl2/sdlgfx.  7 py", line 190, in <module>                                                         8     _funcs[f.name] = _bind(f.name, f.args, f.returns, f.added)                     9   File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/sdl2/dll.py" 10 , line 249, in bind_function                                                      11     raise ValueError(e % (funcname, self._libfile, libver))                       12 ValueError: Could not find function 'SDL_initFramerate' in /data/data/com.termux/ 13 files/usr/lib/libSDL2_gfx.so (SDL2_gfx 1.0.4)

And yes I have built SDL2_gfx version 1.0.4 from the source.
It appears that pysdl2 is unable to find any of the functions in SDL2_gfx shared lib.

**Comment by a-hurst** [comment]
Hi @CAPTAIN1947, I'm amazed pysdl2 runs at all in that environment. Very cool to hear!

If ctypes and basic SDL2 are working fine, my gut instinct would be that SDL2\_gfx was compiled incorrectly: I know that in order to get it to build on ARM Linux you need to explicitly disable MMX during configuration, so maybe it's something along those lines.

Do TTF, image, or mixer functions work okay? If they do, that rules out it being an issue with linked libraries. Also, was SDL2 itself built from source or installed using some sort of package manager? I'd never heard of termux until now, so I don't know much about it.

**Comment by CAPTAIN1947** [comment]
Hello @a-hurst. :)
Yes, the ttf, image and mixer work fine and as I have used pygame on termux for a long time and it works fine there, I don't think they have any problem. And yes the image, ttf, mixer and sdl2 itself are installed from the package manager but gfx is not there yet. So I had to build gfx from source but I used the --disable-mmx option. Also there were some other problems like by it tried to install in \usr\ but apps don't have permission to write there in android so I have to modify the Makefile so that it creates the libs at termux's internal storage i.e /data/data/com.termux/files/usr/lib/.

**Comment by a-hurst** [comment]
Have you tried checking the functions exported by your built library using `nm`? https://stackoverflow.com/questions/4514745/how-do-i-view-the-list-of-functions-a-linux-shared-library-is-exporting

The error you're getting is ctypes looking for the `SDL_initFramerate`function in the binary and not finding it, so either something in the build process has interfered with the function names being exported correctly, or being exported in a way ctypes can handle.

**Comment by CAPTAIN1947** [comment]
Anyways.... I did a clean install of both gfx and pysdl2, and also removed pysdl2-dll as it was doing nothing in termux. And now gfx seems to work and I am able to draw circles and other aa primitives. Thanks a lot for responding so quickly and maintaining this project. It's really cool to have a working sdl2 wrapper in python. 
I think this issue can be closed now. Thanks Again. :)
